version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react"
    versions:
    - "> 16.14.2"
  - dependency-name: "@types/react-dom"
    versions:
    - "> 16.9.10"
