language: node_js

node_js:
  - 12

cache:
  directories:
  - node_modules

script:
  - yarn docs:build

deploy:
  provider: pages
  cleanup: false
  token: $TRAVIS_TOKEN_KEY
  local_dir: docs-dist
  on:
    branch: main
